name: Deploy Angular App to Hostinger

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Angular application
      - name: Build Angular application
        run: npm run ng build --configuration=production
        # Verifica que el output coincida con "SOURCE" más abajo

      # 5️⃣ Deploy usando SCP
      - name: Deploy to Hostinger via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}       # ej. 194.195.84.168
          username: ${{ secrets.HOSTINGER_USER }}   # ej. u364043120
          key: ${{ secrets.HOSTINGER_SSH_KEY }}     # clave privada sin passphrase
          port: ${{ secrets.HOSTINGER_PORT }}       # ej. 65002
          source: "dist/help-desk-module/browser/*" # ruta de tu build
          target: "domains/enlacetecnologias.mx/public_html/helpdesk/"

      # 6️⃣ Health-check
      - name: Wait for health check and perform it
        run: |
          echo "Esperando 10 segundos para que el servidor se estabilice..."
          sleep 10

          echo "Realizando Health Check en https://helpdesk.enlacetecnologias.mx..."
          if curl -fsL -o /dev/null --max-time 15 https://helpdesk.enlacetecnologias.mx; then
            echo "✔️ Health Check exitoso: La aplicación está funcionando correctamente."
          else
            echo "❌ Error en Health Check: la aplicación no respondió correctamente."
            exit 1
          fi
